version: "3.5"

services:
  flip-api:
    build: ./flip-api
    image: flip-api-image
    container_name: flip-api
    restart: unless-stopped
    tty: true
    environment:
      - DB_CONNECTION=${POSTGRES_DB_CONNECTION}
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_DATABASE=${POSTGRES_DB_DATABASE}
      - DB_USERNAME=${POSTGRES_DB_USERNAME}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - "${FLIP_API_PORT}:${FLIP_PORT}"
    volumes:
      - type: bind
        source: ../laravel
        target: /var/www/html
      - type: volume
        source: apache-logs
        target: /var/log/apache2
    networks:
      - flip-network
    depends_on:
      - flip-postgres

  flip-postgres:
    image: postgres:14.1
    container_name: flip-postgres
    restart: always
    tty: true
    ports:
      - "${POSTGRES_DB_HOST_PORT}:${POSTGRES_DB_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_DATABASE}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    networks:
      - flip-network

    
volumes:
  apache-logs:
    name: flip-apache-logs
  postgres-data:
    name: flip-postgres-data
  nginx-conf:
  nginx-host:
  nginx-html:
  nginx-certs:
  acme:

networks:
  flip-network:
    external: true

    

